### ISSUE TITLE
UI issues in swap view

### ISSUE THREAD

**Issue by skzv** [thorchain/asgardex-electron#1300]
Noticed some issues in the swap view:

- leading zero is not removed by backspace
- after a certain number of zeros are appended, there's some sort of string parsing or conversion error, and the amount of btc decreases to zero instead of being converted properly
- See video showing issues: https://user-images.githubusercontent.com/11140296/114238106-cac6e380-991f-11eb-9e2e-be9638285ba8.mov

- [x] Using most recent release (0.1.0-alpha.2)
- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

- should be able to backspace until the field is empty
- rune to btc value should be converted correctly

## Current Behavior

- leading zero is not removed by backspace
- after a certain number of zeros are appended, there's some sort of string parsing or conversion error, and the amount of btc decreases to zero instead of being converted properly

## Possible Solution

- field/string manipulation errors

## Steps to Reproduce (for bugs)

Open rune <-> btc swap view, and try entering a value with many zeros, or backspacing until the field is empty

## Context

poor UX taints user trust, and the incorrect conversion is very concerning

## Your Environment

Most recent alpha release

https://user-images.githubusercontent.com/11140296/114238106-cac6e380-991f-11eb-9e2e-be9638285ba8.mov

**Comment by thatStrangeGuyThorchain** [comment]
hey @skzv.
related to yours `after a certain number of zeros are appended, there's some sort of string parsing or conversion error, and the amount of btc decreases to zero instead of being converted properly` seems it caused by big slippage amount (according to your video it's close to 100%) and that's why resulted estimated result is close to zero value. we already have a task [[Swap] Slip limit exceeded check #1105](https://github.com/thorchain/asgardex-electron/issues/1105) for that.
