### ISSUE TITLE
[Swap] Add identifier for ASGARDEX to `swap` memo

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#1615]
ASGDX ID: `999`
Memo: `SWAP:{ASSET}:{DESTADDR}:12341999` (slightly adjust limit to id `999`)

Depends on #1105

**Comment by gromgromgrom** [comment]
Does it make sense to make this cahnge the part of [asgardex-util](https://gitlab.com/thorchain/asgardex-common/asgardex-util) package?

**Comment by veado** [comment]
[getSwapMemo](https://gitlab.com/thorchain/asgardex-common/asgardex-util/-/blob/master/src/memo.ts#L16) has already all data we need to pass: `{ asset: Asset; address?: string; limit?: BaseAmount }`. The `identifier` `999` will be the last three digits of `limit`. However, before we can add a `slip limit` to the memo, we do need to implement a slip limit protection #1105 (we don't have such protection in ASGDX right now)

**Comment by pantheons1** [comment]
july 16,2021
is there an issue with your swapping - since the calulations are way off .

did a swap in Asgardex from btc to rune / rune to btc  DID HAVE $3881.57 but after swapping around i now left with $226.40 .. see transaction below ( missing 3655.17 )

CHAOSNET
POOLS
WALLET
$ USD
ASSETS  SHARES  BONDS  HISTORY
DETAIL	DATE	DETAIL   
SWAP
INᚱ 7.01576684⚡ 83,337OUT
07/14/2021 19:34	
SWAP
INᚱ 710.71562954₿ 0.12373175OUT
07/14/2021 19:16	
SWAP
IN₿ 0.12543178ᚱ 717.77828709OUT
07/14/2021 18:53	
SWAP
INᚱ 6.67812181⚡ 108,871OUT
07/14/2021 16:48	
SWAP
INᚱ 334.88609039₿ 0.05892867OUT
07/14/2021 16:45	
SWAP
IN₿ 0.08257076ᚱ 341.7205004OUT
06/15/2021 22:02	

paddress
bc1q528rrkmhdhpdhqh0c4ll0nl3rjtx8txgjfa3kd
thor1lfe48vgxxmmmawrsuqe4hpak2qfaetvvsua9su
0x9c02679cca11ad94044083f9b9a161571acf5468

please contact me @ pantheons @ gmail.com

**Comment by pantheons1** [comment]
Why did you close this issue, when it’s not resolved yet !!
I still have not got my crypto amount corrected via $4847.868
In eth which you show only .605 crypto !

Please reply
Thxs
Rob

**Comment by veado** [comment]
> Why did you close this issue, when it’s not resolved yet !! I still have not got my crypto amount corrected via $4847.868 In eth which you show only .605 crypto ! Please reply Thxs Rob

Pls note: This issue here (#1615) has nothing to do with #1636, which is still open. You got an info about closing this issue here just because [you have added a duplicated message ^](https://github.com/thorchain/asgardex-electron/issues/1615#issuecomment-881363939) before.

**Comment by pantheons1** [comment]
O ok, thxs

**Comment by pantheons1** [comment]
Any update on this issue, notice no change after upgrade?

Thxs
Rob
