### ISSUE TITLE
UST and XRUNE balances do not show up in testnet wallet

### ISSUE THREAD

**Issue by mogarchy** [thorchain/asgardex-electron#1788]
## Prerequisites
Have either UST or XRUNE in your testnet wallet or swap for them

## Expected Behavior
Actual available balance should show like for other assets

## Current Behavior
Assets do not show in wallet at all or while attempting to make swaps
These screenshots are from the same wallet on SKIP and ASGARDEX Desktop respectively
![image](https://user-images.githubusercontent.com/45055276/134721278-5f326f6e-8307-4bae-baff-a6d14de9f3a0.png)
![image](https://user-images.githubusercontent.com/45055276/134721364-7cd5f6f4-2875-4d28-9dbf-a5f94f22235c.png)

## Steps to Reproduce

1. Transfer or swap XRUNE or UST to your testnet wallet
2. Verify they are the assets are in your wallet (use etherscan or SKIP testnet). 
3. Refresh your ASGARDEX wallet and verify the assets are not showing up

## Your Environment - Release Version (skip if not using a release version)
v0.4.0 Desktop on multiple OS

**Comment by veado** [comment]
@mogarchy Thanks again for opening this issue. 

Some technical background why some ERC20 assets have not been shown in the wallet on `testnet`: Balances for ERC20 are loaded in a different way for (1) `chaosnet` and (2) `testnet` by using `xchain-ethereum`. For (1) one requests is needed only (via Ethplorer - [code](https://github.com/xchainjs/xchainjs-lib/blob/ead3b1b68a53ec504306a065e3ee4d462e22302c/packages/xchain-ethereum/src/client.ts#L314)), but for (2) as many as assets the wallet have (via Etherscan - [code](https://github.com/xchainjs/xchainjs-lib/blob/ead3b1b68a53ec504306a065e3ee4d462e22302c/packages/xchain-ethereum/src/client.ts#L337-L362)). Since we don't know which assets an user has in the wallet, we have hard-coded ERC20 assets for `testnet` in ASGARDEX ([code](https://github.com/thorchain/asgardex-electron/blob/8ea1c10dfe2732edc8747275b96ae59dbde589e3/src/renderer/const.ts#L81-L92)),
