### ISSUE TITLE
Difficulties testing locally (on linux) - keystore issues

### ISSUE THREAD

**Issue by cryptotester** [thorchain/asgardex-electron#2016]
Trying to build the source code and run it locally, but it doesn't seem to load the keystore correctly.

## Issue description

Note, I'm using a very old keystore, I think from April 2021.

- I followed the instructions in the readme. yarn, yarn prebuild etc.
- I copied an existing keystore I'm using with thorswap and the release version of asgardex-electron, as follows (mkdir was necessary, as the `storage` subfolder was missing): `mkdir ~/.config/Electron/storage/ && cp my-keystore.txt ~/.config/Electron/storage/keystore.json`
- I created in the same folder (git repo folder) a `.env` file containg `REACT_APP_WALLET_PASSWORD=my_keystore_password`
- I run `yarn dev`
- I browse to http://localhost:3000/
- I get this error:
![image](https://user-images.githubusercontent.com/49552918/148994868-ccb74606-7638-4fe8-b015-d3e340d214e5.png)

Thanks for letting me know what to try to use my keystore locally... cheers

## Your Environment

Ubuntu Linux 20.04
NodeJS 16

**Comment by veado** [comment]
> I browse to http://localhost:3000/
Since ASGARDEX is running within an `Electron` environment using `Node` behind the scenes to get access to the file system, you can't run it in a browser. Pls try to follow instructions how to run the Electron app locally by following instructions in the README. If you still have issues, feel free to join THORChains Discord (#asgardex-desktop) https://discord.gg/4AcdkEBQ to have a chat there ...
