### ISSUE TITLE
User should be able to input swap amount manually

### ISSUE THREAD

**Issue by sourovafrin** [thorchain/asgardex-electron#2530]
## Description

In a swap, the user is unable to input the swap amount. So when there is a network problem the user will be unable to swap through the app. Which happened today to me. There was some problem loading the balance of ltc and doge
![Screenshot from 2023-01-27 18-41-57](https://user-images.githubusercontent.com/38147368/215090226-1d60b4e5-83f0-4ef0-b843-cd628ff48c48.png)

And for that reason, it was showing a 0 balance when I tried to swap even though in actuality I had a balance in my address
![Screenshot from 2023-01-27 17-27-22](https://user-images.githubusercontent.com/38147368/215090493-73746ef5-7e93-418d-b46b-0c7e00218444.png)

And when I tried to input manual amount I just couldn't. This makes a user unable to swap. If a user could manually input the amount the swap could happen if there is a balance, otherwise it could just fail.
![asgardex](https://user-images.githubusercontent.com/38147368/215090920-8dc73b10-686a-4d60-9352-f078630f594e.gif)

So an option to manually input the amount on both the swap and receiving amount would be a great addition.

**Comment by veado** [comment]
Swap input depends on wallet balances. If a balance is zero an input can't be greater than zero. 

Pls note: Due an issue of a third party API (Sochain), balances for UTXO chains are not available. xchain-* devs are working on a fix, see following threads/discussions at Discord:
- #asgardex-desktop https://discord.com/channels/838986635756044328/839002220942721024/1068075653657792522
- #xchainjs https://discord.com/channels/838986635756044328/842252939149967382/1067776805685186621

**Comment by sourovafrin** [comment]
I thought in this case letting a transaction happen and yielding the error could be a better way. Bcz if the balance is zero or less than the input amount, the tx is not going to happen anyway

**Comment by veado** [comment]
Balances are needed to calculate `max`, which depends on frees. Furthermore balances are checked, especially for BTC, to let send values of confirmed balances only. It' to protect THORChain for issues, but also for users to avoid burning fees in case of sending amounts they don't have.

However, I see your point. IMO the issue is not a check of zero balances, but the lack of supporting different APIs in `xchain-*` (that's the lib ASGARDEX is using behind the scenes). If this will be improved, users of ASGARDEX could switch to another provider easily. 

For more question feel free to join #asgardex-desktop channel at Discord.
