### ISSUE TITLE
Link Mnemonic view from ImportsView 

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#273]
Currently Mnemonic View is not accessible, but it should be linked from "ImportsView" ([layout]( https://www.figma.com/file/LgRqZCGMShZ2mJ702MIqyV/ASGARDEX-2020?node-id=1306%3A6254) )

**Comment by thatStrangeGuyThorchain** [comment]
@veado what is logic for Mnemonic ? is user available to type a string manully ?
if yes what is a scenario for user interaction ?

**Comment by thorchain-admin** [comment]
@thatStrangeGuyThorchain 

Mnemonics are 12 or 24 word phrases that come from the BIP39 word list of 2048 English words (https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt). 

The first 11 (or 22) words are entropy, the final 1 (2) words are a checksum, so they user MUST not pick their own words. 

they should use the BIP39 library to `generateMnemonic()` https://iancoleman.io/bip39/ which will return a valid phrase. 

However, they may have previously generated a valid phrase in another wallet and have funds on it. In which case they can add it and call `validateMnemonic(phrase)` in order to check that it is valid. 

----
The logic is:

Generate Phrase:
1) user clicks "new" and a list of 12 words appear. 
2) They then need to copy it down separately (secure notepad) then re-enter it
3) To make (2) easier, then can just select from a mix of words and demonstrate it is in correct order

Import Phrase:
1) User enters their 12 word phrase, it is simply checked

**Comment by thorchain-admin** [comment]
Note: we are using our own library `asgardex-crypto` to handle everything, please review:

https://gitlab.com/thorchain/asgardex-common/asgardex-crypto#basic-usage
