### ISSUE TITLE
Release V0.0.4 - page load caused 404 on png

### ISSUE THREAD

**Issue by GrassRootsCrypto** [thorchain/asgardex-electron#895]
- [ ] Using yarn dev
- [ ] Using node 12.14.4
- [ ] Using an up-to-date Release V0.0.4

## Expected Behavior
Pool page loads without any error console errors

## Current Behavior
Every time the pool page is loaded, or Refresh button is pressed a 404 is produced. This happens when entering and existing a pool. 

https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/binance/assets/BUSD-BAF/logo.png 

![image](https://user-images.githubusercontent.com/40199525/107735314-f033d880-6d46-11eb-8d56-889655548c40.png)

## Possible Solution
Update the call to where the png is located. 

## Steps to Reproduce (for bugs)

1. Create wallet

2. Go to the pools area

3. Move into a pool (any) via + Liquidity Button

4. Same occurs when pressing the back button

**Comment by veado** [comment]
Good catch! 

Currently ASGARDEX loads icons of (almost all) icons from [Trustwallet sources](https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/). Assets names for this sources are based on mainnet, that's why we have 404 in case of testnet. However, we will fix that issue.

# TODO (ASGDX team)

- Prevent 404 in `AssetIcon` for `testnet`
- Extend `AssetIcon` to provide assets of all chains we currently support (not just for Binance)
